# 错误边界

> 在React中，可以通过`Error Boundaries`（错误边界）来捕获错误异常。`Error Boundaries`是一种React组件，它可以在其子组件树的渲染期间捕获JavaScript异常，并且可以渲染出备用UI。React提供了两个生命周期方法来处理错误边界：`componentDidCatch`和`getDerivedStateFromError`
>
> 其中，`componentDidCatch`生命周期方法在错误边界内的任何子组件抛出错误时被调用。它接收两个参数：`error`和`info`。`error`参数表示抛出的错误，`info`参数包含有关组件引发错误的组件堆栈的信息。通常情况下，此方法将记录错误并更新组件的状态以显示备用UI

`componentDidCatch`方法：用于处理错误异常，当子组件抛出错误时，React会在Error [Boundary](https://so.csdn.net/so/search?q=Boundary&spm=1001.2101.3001.7020)中调用`componentDidCatch`方法。在该方法中可以实现错误信息的记录和展示等逻辑

`getDerivedStateFromError`方法：会在`componentDidCatch`方法调用之后调用，用于更新state中的数据。该方法可以返回一个对象来更新组件的状态

## 示例

```tsx
import React from 'react'

// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface Props {
  children: React.ReactNode
}

interface State {
  hasError: boolean
  errorInfo: any
  error: any
}

class ErrorBoundary extends React.Component<Props, State> {
  constructor(props: Props) {
    super(props)
    this.state = { hasError: false, errorInfo: {}, error: {} }
  }

  static getDerivedStateFromError() {
    return { hasError: true }
  }

  componentDidCatch(error: any, errorInfo: any) {
    this.setState(Object.assign({}, this.state, { errorInfo, error }))
  }

  render() {
    if (this.state.hasError) {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment, @typescript-eslint/prefer-ts-expect-error
      // @ts-ignore
      return (
        <div>
          {this.state.errorInfo.componentStack}
          <br />
          {this.state.error.message}
        </div>
      )
    }

    return this.props.children
  }
}

export default ErrorBoundary

```

在上面的示例中，`ErrorBoundary`组件包装了其子组件，并提供了备用UI。如果其中的任何子组件引发错误，则会调用`componentDidCatch`生命周期方法并更新状态以显示备用UI。然后，可以将`ErrorBoundary`组件包装在任何需要捕获错误异常的组件中：

```tsx
import React from 'react';
import ErrorBoundary from './ErrorBoundary';

function App() {
  return (
    <div>
      <h1>Hello, world!</h1>
      <ErrorBoundary>
        <ComponentThatMayThrowAnError />
      </ErrorBoundary>
    </div>
  );
}
```

在上面的示例中，`ComponentThatMayThrowAnError`组件可能会抛出错误，因此将其包装在`ErrorBoundary`组件中，以确保错误得到捕获和处理

## 注意⚠️

1、错误边界可以捕获发生在整个子组件树的渲染期间、生命周期方法以及构造函数中的错误

2、错误边界**无法**捕获以下场景中产生的错误：

- 事件处理
- 异步代码（例如`setTimeout`或`requestAnimationFrame`回调函数）
- 服务端渲染
- 它自身抛出来的错误（并非它的子组件）

3、错误边界的工作方式类似于JavaScript的`catch {}`，不同的地方在于错误边界只针对React组件。**只有 class 组件才可以成为错误边界组件**

4、**错误边界仅可以捕获其子组件的错误**，它无法捕获其自身的错误。如果一个错误边界无法渲染错误信息，则错误会冒泡至最近的上层错误边界，这也类似于 JavaScript 中`catch {}`的工作机制

5、React不需要错误边界来捕获事件处理器中的错误。与render方法和生命周期方法不同，事件处理器不会在渲染期间触发

6、如果你需要在事件处理器内部捕获错误，使用普通的JavaScript`try` / `catch`语句